-- COLOCAR BANCO DE DADOS PEDIDOS EM USO
USE PEDIDOS_LOGITRACK

-- CRIAÇÃO DE UMA NOVA TABELA DE ENTREGAS
CREATE TABLE ENTREGAS (
	ID_PEDIDO INT PRIMARY KEY,
	CLIENTE VARCHAR(100) NOT NULL,
	CIDADE_DESTINO VARCHAR(50) NOT NULL,
	DATA_POSTAGEM DATE,
	VALOR_FRETE DECIMAL(10,2),
	STATUS_ENTREGA VARCHAR(20)
);

-- INSERIR DADOS NA TABELA 
INSERT INTO ENTREGAS (ID_PEDIDO,CLIENTE,CIDADE_DESTINO,DATA_POSTAGEM, VALOR_FRETE, STATUS_ENTREGA)
VALUES
(101, 'Empresa Alfa', 'São Paulo', '2026-04-01', 50.00, 'Entregue'),
(102, 'Beto Moveis', 'Curitiba', '2026-04-02', 120.50, 'Atrasado'),
(103, 'Celia Modas', 'São Paulo', '2026-04-03', 45.00, 'Em Trânsito'),
(104, 'Duda Tech', 'Recife', '2026-04-04', 210.00, 'Em Trânsito'),
(105, 'Engenharia X', 'São Paulo', '2026-04-05', 89.90, 'Atrasado');

-- FILTRAR AS ENTREGAS QUE PODEM GERAR PROBLEMAS ( COMO ATRASADO, EM TRÂNSITO, EXTRAVIADO)  
SELECT CLIENTE,CIDADE_DESTINO,STATUS_ENTREGA
FROM ENTREGAS
WHERE CIDADE_DESTINO='SÃO PAULO'
AND STATUS_ENTREGA <>'ENTREGUE';

-- INSERIR DADOS ENCONTRADOS EM FONTE SECUNDÁRIA
INSERT INTO ENTREGAS (ID_PEDIDO,CLIENTE,CIDADE_DESTINO,DATA_POSTAGEM, VALOR_FRETE, STATUS_ENTREGA)
VALUES
(106, 'Loja Sol', 'Salvador', '2026-04-08', 75.00, 'Em Trânsito');

-- FILTRAR AS ENTREGAS COM FRETES MAIS ALTOS (PROVÁVEIS PRODUTOS MAIS CAROS)
SELECT *
FROM ENTREGAS
WHERE VALOR_FRETE > 100.00;

